
export default {
    // 仓库名字
    namespace: 'list',
    // 仓库
    state: {
        listLi: [{
            title: "客户管理",
            key: "sub1",
            type: "mail",
            itemTitle1: "客户概览",
            itemTitle2: "客户信息系统",
            itemTitle3: "客户用电数据",
            itemKey1: "3",
            itemKey2: "4",
            itemKey3: "5",
        }, {
            title: "零售市场管理",
            key: "sub2",
            type: "mail",
            itemTitle1: "目标客户负荷特征",
            itemTitle2: "预购电成本预算",
            itemTitle3: "零售合同定价",
            itemKey1: "6",
            itemKey2: "7",
            itemKey3: "8",
        }, {
            title: "批发市场管理",
            key: "sub3",
            type: "mail",
            itemTitle1: "日前申报方案",
            itemTitle2: "中长期交易方案",
            itemTitle3: "交易结果查询",
            itemKey1: "9",
            itemKey2: "10",
            itemKey3: "11",
        }, {
            title: "负荷预测",
            key: "sub4",
            type: "mail",
            itemTitle1: "目前负荷预算",
            itemTitle2: "下周负荷预算",
            itemTitle3: "中长期负荷预算",
            itemKey1: "12",
            itemKey2: "13",
            itemKey3: "14",
        }, {
            title: "合同管理",
            key: "sub5",
            type: "mail",
            itemTitle1: "零售合同",
            itemTitle2: "价差购电合同",
            itemTitle3: "价差售电合同",
            itemKey1: "15",
            itemKey2: "16",
            itemKey3: "17",
        }, {
            title: "结算管理",
            key: "sub6",
            type: "mail",
            itemTitle1: "月结算",
            itemTitle2: "现货版",
            itemTitle3: "差价版",
            itemKey1: "18",
            itemKey2: "19",
            itemKey3: "20",
        }, {
            title: "经营分析",
            key: "sub7",
            type: "mail",
            itemTitle1: "利润分析",
            itemTitle2: "收益风险",
            itemTitle3: "零售市场分析",
            itemKey1: "21",
            itemKey2: "22",
            itemKey3: "23",
        }, {
            title: "数据管理",
            key: "sub8",
            type: "mail",
            itemTitle1: "日前申报数据",
            itemTitle2: "现货电价数据",
            itemTitle3: "日志管理",
            itemKey1: "24",
            itemKey2: "25",
            itemKey3: "26",
        }, {
            title: "月度电量申报",
            key: "sub9",
            type: "mail",
            itemTitle1: "电量申报管理",
            itemTitle2: "电厂客户电量申报",
            itemTitle3: "需求申报分析报告",
            itemKey1: "27",
            itemKey2: "28",
            itemKey3: "29",
        }, {
            title: "报表管理",
            key: "sub10",
            type: "mail",
            itemTitle1: "收支总报表",
            itemTitle2: "需求侧响应",
            itemTitle3: "电价数据",
            itemKey1: "30",
            itemKey2: "31",
            itemKey3: "32",
        }, {
            title: "辅助决策",
            key: "sub11",
            type: "mail",
            itemTitle1: "中长期交易测算",
            itemTitle2: "负荷预算",
            itemTitle3: "风险管理",
            itemKey1: "33",
            itemKey2: "34",
            itemKey3: "35",
        }]
    },
    // reducers跟dispatch里面的type
    reducers: {
        addTab(state, action) {
            console.log(state.listLi, action.payload.list)
            // 合并新数组
            state.list = [...state.listLi, ...action.payload.list]
            // 更新仓库state
            return { ...state };
        },
    },
};
